name: MA60 Signal Bot

on:
  schedule:
    - cron: "*/1 * * * *"   # ✔ 每10分钟运行一次
  workflow_dispatch:         # ✔ 保留手动（可选，不影响）

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests pandas

      - name: Run signal script
        run: python signal.py
